# 비슷한 영화 추천 (item-basd filtering)

In [1]:
import os, sys

# 주피터 노트북 환경에서 __file__이 없으므로, 현재 워킹 디렉토리 기준으로 설정
project_root = os.path.abspath(os.path.join(os.getcwd(), '..', '..'))
if project_root not in sys.path:
    sys.path.insert(0, project_root)

In [2]:
from modeling.models.item_based.model import ItemBasedModel

loaded_model = ItemBasedModel.load()
movie_id_list = list(loaded_model.id_mapping.movie_to_idx)

In [3]:
from data_scraping.common import load_movie_data

df_movies = load_movie_data()
df_movies = df_movies[df_movies['movie_id'].isin(movie_id_list)].reset_index(drop=True) # df_movies 중 movie_id가 movie_id_list에 포함된 것만 필터링
df_movies['total_title'] = df_movies.apply(
    lambda row: row['title_tmdb'] if row['title_tmdb'] == row['original_title']
    else f"{row['title_tmdb']} ({row['original_title']})",
    axis=1
)

In [14]:
df_movies[df_movies['total_title'].str.contains("타이타닉")]

,movie_id,title,genres,imdb_id,tmdb_id,adult,backdrop_path,id,title_tmdb,original_title,...,original_language,genre_ids,popularity,release_date,video,vote_average,vote_count,genres_tmdb,language,total_title
781,3403,Raise the Titanic (1980),Drama Thriller,tt0081400,24575.0,False,/k0mwvvXFvBAVTrlYf5D2sETXMHX.jpg,24575,타이타닉 인양,Raise the Titanic,...,en,"[28, 12, 18, 53]",3.2231,1980-08-01,False,5.3,106.0,액션 모험 드라마 스릴러,영어,타이타닉 인양 (Raise the Titanic)
7828,3405,"Night to Remember, A (1958)",Action Drama,tt0051994,10971.0,False,/xznEB3uLBjPpqdrxvqeVYG3i6ow.jpg,10971,타이타닉호의 비극,A Night to Remember,...,en,"[18, 28, 36]",1.8872,1958-07-03,False,7.7,274.0,드라마 액션 역사,영어,타이타닉호의 비극 (A Night to Remember)
13019,1721,Titanic (1997),Drama Romance,tt0120338,597.0,False,/sCzcYW9h55WcesOqA12cgEr9Exw.jpg,597,타이타닉,Titanic,...,en,"[18, 10749]",23.9724,1997-11-18,False,7.9,26432.0,드라마 로맨스,영어,타이타닉 (Titanic)
15407,3404,Titanic (1953),Action Drama,tt0046435,16535.0,False,/ahbx803wrITvlSjxLyp0Sfkzy3s.jpg,16535,타이타닉의 최후,Titanic,...,en,"[18, 10749]",5.8485,1953-04-11,False,6.6,150.0,드라마 로맨스,영어,타이타닉의 최후 (Titanic)

In [15]:
recommendations = loaded_model.predict(
                movie_id='1721',
                top_n=10,
                return_scores=False
            )
recommendations

['1580', '2762', '356', '1682', '1704', '2028', '1270', '2571', '4306', '1097']

In [ ]:
result_df = df_movies[df_movies['movie_id'].isin(recommendations)]
result_df

,movie_id,title,genres,imdb_id,tmdb_id,adult,backdrop_path,id,title_tmdb,original_title,...,original_language,genre_ids,popularity,release_date,video,vote_average,vote_count,genres_tmdb,language,total_title
67,1580,Men in Black (a.k.a. MIB) (1997),Action Comedy Sci-Fi,tt0119654,607.0,False,/1GJvBE7UWU1WOVi0XREl4JQc7f8.jpg,607,맨 인 블랙,Men in Black,...,en,"[28, 12, 35, 878]",10.4852,1997-07-02,False,7.214,14365.0,액션 모험 코미디 SF,영어,맨 인 블랙 (Men in Black)
1427,1704,Good Will Hunting (1997),Drama Romance,tt0119217,489.0,False,/bpV8wn48s82au37QyUJ51S7X2Vf.jpg,489,굿 윌 헌팅,Good Will Hunting,...,en,[18],12.1061,1997-12-05,False,8.156,13218.0,드라마,영어,굿 윌 헌팅 (Good Will Hunting)
1748,356,Forrest Gump (1994),Comedy Drama Romance War,tt0109830,13.0,False,/67HggiWaP9ZLv5sPYmyRV37yAJM.jpg,13,포레스트 검프,Forrest Gump,...,en,"[35, 18, 10749]",65.2277,1994-06-23,False,8.464,28783.0,코미디 드라마 로맨스,영어,포레스트 검프 (Forrest Gump)
3663,2762,"Sixth Sense, The (1999)",Drama Horror Mystery,tt0167404,745.0,False,/6TjllWT3cGrPFyqDXurVZ3L8bBi.jpg,745,식스 센스,The Sixth Sense,...,en,"[9648, 53, 18]",12.7616,1999-08-06,False,7.949,12341.0,미스터리 스릴러 드라마,영어,식스 센스 (The Sixth Sense)
3726,1097,E.T. the Extra-Terrestrial (1982),Children Drama Sci-Fi,tt0083866,601.0,False,/mXLVA0YL6tcXi6SJSuAh9ONXFj5.jpg,601,이티,E.T. the Extra-Terrestrial,...,en,"[878, 12, 10751, 14]",9.8700,1982-06-11,False,7.512,11622.0,SF 모험 가족 판타지,영어,이티 (E.T. the Extra-Terrestrial)
5575,4306,Shrek (2001),Adventure Animation Children Comedy Fantasy Ro...,tt0126029,808.0,False,/40Wtp7kMG6mZ4d5T1jfrd8qrvD4.jpg,808,슈렉,Shrek,...,en,"[16, 35, 14, 12, 10751]",22.3544,2001-05-18,False,7.752,18075.0,애니메이션 코미디 판타지 모험 가족,영어,슈렉 (Shrek)
7332,1270,Back to the Future (1985),Adventure Comedy Sci-Fi,tt0088763,105.0,False,/5bzPWQ2dFUl2aZKkp7ILJVVkRed.jpg,105,빽 투 더 퓨쳐,Back to the Future,...,en,"[12, 35, 878]",23.2010,1985-07-03,False,8.321,21016.0,모험 코미디 SF,영어,빽 투 더 퓨쳐 (Back to the Future)
14861,1682,"Truman Show, The (1998)",Comedy Drama Sci-Fi,tt0120382,37165.0,False,/rmiG2uwcNoGFmBKMoa1pIcf514L.jpg,37165,트루먼 쇼,The Truman Show,...,en,"[35, 18]",13.8399,1998-06-04,False,8.148,19438.0,코미디 드라마,영어,트루먼 쇼 (The Truman Show)
17097,2028,Saving Private Ryan (1998),Action Drama War,tt0120815,857.0,False,/rW2xRFlJRbTnBJlQTSjQmjevIwb.jpg,857,라이언 일병 구하기,Saving Private Ryan,...,en,"[18, 36, 10752]",10.9500,1998-07-24,False,8.221,16615.0,드라마 역사 전쟁,영어,라이언 일병 구하기 (Saving Private Ryan)
18096,2571,"Matrix, The (1999)",Action Sci-Fi Thriller,tt0133093,603.0,False,/oMsxZEvz9a708d49b6UdZK1KAo5.jpg,603,매트릭스,The Matrix,...,en,"[28, 878]",22.0942,1999-03-31,False,8.200,26948.0,액션 SF,영어,매트릭스 (The Matrix)

# CF. 사용자 기반 추천

In [4]:
from modeling.models.svd.model import SVDModel

svd_model = SVDModel.load_model(use_total_data=True)

2025-11-04 00:42:37,053 - modeling.models.svd.model - INFO - ================================================================================
2025-11-04 00:42:37,053 - modeling.models.svd.model - INFO - 🔧 SVDModel 초기화 시작
2025-11-04 00:42:37,053 - modeling.models.svd.model - INFO - 📄 Config 파일 경로: /Users/user/Desktop/movie_recommendation/modeling/models/config.yaml
2025-11-04 00:42:37,056 - modeling.models.svd.model - INFO -
📋 모델 설정:
2025-11-04 00:42:37,057 - modeling.models.svd.model - INFO -   - n_factors: 20
2025-11-04 00:42:37,057 - modeling.models.svd.model - INFO -   - n_epochs: 8
2025-11-04 00:42:37,057 - modeling.models.svd.model - INFO -   - lr_all: 0.005
2025-11-04 00:42:37,057 - modeling.models.svd.model - INFO -   - reg_all: 0.02
2025-11-04 00:42:37,057 - modeling.models.svd.model - INFO -   - random_state: 42
2025-11-04 00:42:37,057 - modeling.models.svd.model - INFO -   - verbose: True
2025-11-04 00:42:37,058 - modeling.models.svd.model - INFO -   - test_size: 0.2
2025-11-04 00:42:37,058 - modeling.models.svd.model - INFO -   - rating_scale: [0.5, 5.0]
2025-11-04 00:42:37,058 - modeling.models.svd.model - INFO -   - use_integrated_data: True
2025-11-04 00:42:37,058 - modeling.models.svd.model - INFO - ✅ SVDModel 초기화 완료
2025-11-04 00:42:37,058 - modeling.models.svd.model - INFO - ================================================================================
2025-11-04 00:42:37,059 - modeling.models.svd.model - INFO - 🔨 모델 객체 생성 중... (use_total_data=True)
2025-11-04 00:42:37,059 - modeling.models.svd.model - INFO - 📥 전체 데이터셋 로드 중...

✅ 캐시에서 Train/Test 데이터 로드: cache_train_70e1b2a1d2b3.csv
2025-11-04 00:43:21,238 - modeling.models.svd.model - INFO - ✅ 모델 객체 생성 완료 (사용자: 200932, 아이템: 18514)
2025-11-04 00:43:21,241 - modeling.models.svd.model - INFO - 📂 파라미터 로드 시작: /Users/user/Desktop/movie_recommendation/modeling/models/svd/model-data/svd_params.npz
2025-11-04 00:43:21,363 - modeling.models.svd.model - INFO - ✅ SVD 파라미터 로드 완료: /Users/user/Desktop/movie_recommendation/modeling/models/svd/model-data/svd_params.npz

In [5]:
svd_model.predict("0", "1000")

Prediction(uid='0', iid='1000', r_ui=None, est=3.2793671682910497, details={'was_impossible': False})

In [6]:
import pandas as pd

trainset = svd_model.trainset
df_trainset = pd.DataFrame([
    {
        'user_id': trainset.to_raw_uid(u),
        'movie_id': trainset.to_raw_iid(i),
        'rating': r
    }
    for (u, i, r) in trainset.all_ratings()
])

df_trainset.head()

  user_id movie_id  rating
0       1      232     5.0
1       1      260     5.0
2       1     1183     4.0
3       1     2502     3.0
4       1     1210     2.0

In [7]:
top_watched = df_trainset.loc[df_trainset['user_id'] == "2"].nlargest(10, 'rating')
top_watched = df_movies.merge(top_watched[['movie_id']], on='movie_id', how='inner')
top_watched

,movie_id,title,genres,imdb_id,tmdb_id,adult,backdrop_path,id,title_tmdb,original_title,...,original_language,genre_ids,popularity,release_date,video,vote_average,vote_count,genres_tmdb,language,total_title
0,318,"Shawshank Redemption, The (1994)",Crime Drama,tt0111161,278.0,False,/v8xVDqt8uCul3c3mgx4VpGCwxJC.jpg,278,쇼생크 탈출,The Shawshank Redemption,...,en,"[18, 80]",35.3465,1994-09-23,False,8.712,29130.0,드라마 범죄,영어,쇼생크 탈출 (The Shawshank Redemption)
1,34,Babe (1995),Children Drama,tt0112431,9598.0,False,/agkZziO4ZPAsVfKUrJD68lys08P.jpg,9598,꼬마 돼지 베이브,Babe,...,en,"[14, 18, 35, 10751]",5.3781,1995-07-18,False,6.251,3021.0,판타지 드라마 코미디 가족,영어,꼬마 돼지 베이브 (Babe)
2,364,"Lion King, The (1994)",Adventure Animation Children Drama Musical IMAX,tt0110357,8587.0,False,/wXsQvli6tWqja51pYxXNG1LFIGV.jpg,8587,라이온 킹,The Lion King,...,en,"[10751, 16, 18, 12]",13.5684,1994-06-15,False,8.255,19120.0,가족 애니메이션 드라마 모험,영어,라이온 킹 (The Lion King)
3,218,Boys on the Side (1995),Comedy Drama,tt0112571,9382.0,False,/gja1HJCm1byNL6AsM8BSv6LveNk.jpg,9382,보이즈 온 더 사이드,Boys on the Side,...,en,"[35, 18]",3.0991,1995-02-03,False,6.400,242.0,코미디 드라마,영어,보이즈 온 더 사이드 (Boys on the Side)
4,282,Nell (1994),Drama,tt0110638,1945.0,False,/3Nv0jfMQvGKv4wL9rESZeyEw9Wl.jpg,1945,넬,Nell,...,en,"[18, 53]",4.0664,1994-12-23,False,6.558,530.0,드라마 스릴러,영어,넬 (Nell)
5,595,Beauty and the Beast (1991),Animation Children Fantasy Musical Romance IMAX,tt0101414,10020.0,False,/fW4ZCoEZRBqLAJGFQ2g5AdAfPQR.jpg,10020,미녀와 야수,Beauty and the Beast,...,en,"[10749, 10751, 16, 14]",11.2792,1991-10-22,False,7.700,10367.0,로맨스 가족 애니메이션 판타지,영어,미녀와 야수 (Beauty and the Beast)
6,185,"Net, The (1995)",Action Crime Thriller,tt0113957,1642.0,False,/lmjReP9aoEZFFyqDP1JP4F0Ohsf.jpg,1642,네트,The Net,...,en,"[80, 18, 9648, 53, 28]",3.5974,1995-07-28,False,6.036,1444.0,범죄 드라마 미스터리 스릴러 액션,영어,네트 (The Net)
7,225,Disclosure (1994),Drama Thriller,tt0109635,8984.0,False,/4A0f1oqkJLohy8LXjmJpops7CMB.jpg,8984,폭로,Disclosure,...,en,"[53, 18, 80]",5.3882,1994-12-09,False,6.258,1229.0,스릴러 드라마 범죄,영어,폭로 (Disclosure)
8,186,Nine Months (1995),Comedy Romance,tt0113986,11472.0,False,/4snl08qYXCUti8JBD2qeCV5kktX.jpg,11472,나인 먼쓰,Nine Months,...,en,"[10749, 35]",3.3935,1995-07-12,False,5.700,676.0,로맨스 코미디,영어,나인 먼쓰 (Nine Months)
9,500,Mrs. Doubtfire (1993),Comedy Drama,tt0107614,788.0,False,/sTgavNm82pTaZR9U2NQZ1J2FrJz.jpg,788,미세스 다웃파이어,Mrs. Doubtfire,...,en,"[35, 18, 10751]",6.6120,1993-11-24,False,7.194,6382.0,코미디 드라마 가족,영어,미세스 다웃파이어 (Mrs. Doubtfire)

In [15]:
# 안본 영화 추천 빠르게: Pandas의 isin 활용, set 변환 최소화
user_id = '2'
user_watched_movies = df_trainset.loc[df_trainset['user_id'] == user_id, 'movie_id']
candidate_mask = ~df_movies['movie_id'].isin(user_watched_movies)
candidate_movie_ids = df_movies.loc[candidate_mask, 'movie_id']

In [16]:
# candidate_movie_id를 하나씩 넣어서 예측값 뽑아내고 높은 평점으로 정렬하는 코드
predictions = []
for movie_id in candidate_movie_ids.values:
    pred = svd_model.predict(user_id, movie_id)
    predictions.append((movie_id, pred.est))

# 예측값으로 정렬
sorted_predictions = sorted(predictions, key=lambda x: x[1], reverse=True)

# 상위 10개 추천 영화 ID 추출
top_n = 10
top_movie_ids = [movie_id for movie_id, est in sorted_predictions[:top_n]]

# 추천 영화 DataFrame 생성
recommendations = df_movies[df_movies['movie_id'].isin(top_movie_ids)].copy()
recommendations['pred_rating'] = recommendations['movie_id'].map(dict(sorted_predictions))
recommendations = recommendations.sort_values('pred_rating', ascending=False)
recommendations.reset_index(drop=True, inplace=True)
recommendations

,movie_id,title,genres,imdb_id,tmdb_id,adult,backdrop_path,id,title_tmdb,original_title,...,genre_ids,popularity,release_date,video,vote_average,vote_count,genres_tmdb,language,total_title,pred_rating
0,1035,"Sound of Music, The (1965)",Musical Romance,tt0059742,15121.0,False,/y9M9xO78SHf43pK5TOgfOeQRHXj.jpg,15121,사운드 오브 뮤직,The Sound of Music,...,"[18, 10751, 10402, 10749]",5.9941,1965-03-29,False,7.700,3471.0,드라마 가족 음악 로맨스,영어,사운드 오브 뮤직 (The Sound of Music),5.000000
1,88125,Harry Potter and the Deathly Hallows: Part 2 (...,Action Adventure Drama Fantasy Mystery IMAX,tt1201607,12445.0,False,/n5A7brJCjejceZmHyujwUTVgQNC.jpg,12445,해리 포터와 죽음의 성물 2,Harry Potter and the Deathly Hallows: Part 2,...,"[14, 12]",15.4612,2011-07-12,False,8.100,21381.0,판타지 모험,영어,해리 포터와 죽음의 성물 2 (Harry Potter and the Deathly ...,4.991000
2,160718,Piper (2016),Animation,tt5613056,399106.0,False,/4GWYk5VP9qu1rNSeNAwNaBy9mwS.jpg,399106,파이퍼,Piper,...,"[10751, 16]",4.6570,2016-06-16,False,8.152,1685.0,가족 애니메이션,영어,파이퍼 (Piper),4.971916
3,98491,Paperman (2012),Animation Comedy Romance,tt2388725,140420.0,False,/48v92pR5a1JeczlrCwnr1eQBN2j.jpg,140420,페이퍼맨,Paperman,...,"[16, 10751, 10749]",2.1861,2012-11-02,False,7.995,1756.0,애니메이션 가족 로맨스,영어,페이퍼맨 (Paperman),4.951528
4,81834,Harry Potter and the Deathly Hallows: Part 1 (...,Action Adventure Fantasy IMAX,tt0926084,12444.0,False,/AqLcLsGGTzAjm3pCCq0CZCQrp6m.jpg,12444,해리 포터와 죽음의 성물 1,Harry Potter and the Deathly Hallows: Part 1,...,"[12, 14]",16.0929,2010-11-17,False,7.700,19830.0,모험 판타지,영어,해리 포터와 죽음의 성물 1 (Harry Potter and the Deathly ...,4.940675
5,2125,Ever After: A Cinderella Story (1998),Comedy Drama Romance,tt0120631,9454.0,False,/lhpokM60CnLWcNETQqKMz2q9ryL.jpg,9454,에버 애프터,EverAfter,...,"[18, 10749, 35]",3.3908,1998-07-31,False,7.439,1527.0,드라마 로맨스 코미디,영어,에버 애프터 (EverAfter),4.937487
6,261955,The Rescue (2021),Documentary Thriller,tt9098872,680058.0,False,/gOBKWe6lHlt8srk11TFlDuBtl0H.jpg,680058,위대한 구조,The Rescue,...,"[99, 18]",4.2165,2021-10-08,False,7.942,242.0,다큐멘터리 드라마,영어,위대한 구조 (The Rescue),4.927864
7,166643,Hidden Figures (2016),Drama,tt4846340,381284.0,False,/rfkIeCaIHhN3K5wjJJqKmfUjYp8.jpg,381284,히든 피겨스,Hidden Figures,...,"[18, 36]",54.8357,2016-12-10,False,8.050,10146.0,드라마 역사,영어,히든 피겨스 (Hidden Figures),4.924833
8,69844,Harry Potter and the Half-Blood Prince (2009),Adventure Fantasy Mystery Romance IMAX,tt0417741,767.0,False,/urDWNffjwmNi5IQaezw9GwqkUXa.jpg,767,해리 포터와 혼혈왕자,Harry Potter and the Half-Blood Prince,...,"[12, 14]",15.7831,2009-07-15,False,7.682,20221.0,모험 판타지,영어,해리 포터와 혼혈왕자 (Harry Potter and the Half-Blood P...,4.914753
9,2324,Life Is Beautiful (La Vita è bella) (1997),Comedy Drama Romance War,tt0118799,637.0,False,/6aNKD81RHR1DqUUa8kOZ1TBY1Lp.jpg,637,인생은 아름다워,La vita è bella,...,"[35, 18]",9.5737,1997-12-20,False,8.440,13604.0,코미디 드라마,이탈리아어,인생은 아름다워 (La vita è bella),4.906753

In [17]:
recommendations

,movie_id,title,genres,imdb_id,tmdb_id,adult,backdrop_path,id,title_tmdb,original_title,...,genre_ids,popularity,release_date,video,vote_average,vote_count,genres_tmdb,language,total_title,pred_rating
0,1035,"Sound of Music, The (1965)",Musical Romance,tt0059742,15121.0,False,/y9M9xO78SHf43pK5TOgfOeQRHXj.jpg,15121,사운드 오브 뮤직,The Sound of Music,...,"[18, 10751, 10402, 10749]",5.9941,1965-03-29,False,7.700,3471.0,드라마 가족 음악 로맨스,영어,사운드 오브 뮤직 (The Sound of Music),5.000000
1,88125,Harry Potter and the Deathly Hallows: Part 2 (...,Action Adventure Drama Fantasy Mystery IMAX,tt1201607,12445.0,False,/n5A7brJCjejceZmHyujwUTVgQNC.jpg,12445,해리 포터와 죽음의 성물 2,Harry Potter and the Deathly Hallows: Part 2,...,"[14, 12]",15.4612,2011-07-12,False,8.100,21381.0,판타지 모험,영어,해리 포터와 죽음의 성물 2 (Harry Potter and the Deathly ...,4.991000
2,160718,Piper (2016),Animation,tt5613056,399106.0,False,/4GWYk5VP9qu1rNSeNAwNaBy9mwS.jpg,399106,파이퍼,Piper,...,"[10751, 16]",4.6570,2016-06-16,False,8.152,1685.0,가족 애니메이션,영어,파이퍼 (Piper),4.971916
3,98491,Paperman (2012),Animation Comedy Romance,tt2388725,140420.0,False,/48v92pR5a1JeczlrCwnr1eQBN2j.jpg,140420,페이퍼맨,Paperman,...,"[16, 10751, 10749]",2.1861,2012-11-02,False,7.995,1756.0,애니메이션 가족 로맨스,영어,페이퍼맨 (Paperman),4.951528
4,81834,Harry Potter and the Deathly Hallows: Part 1 (...,Action Adventure Fantasy IMAX,tt0926084,12444.0,False,/AqLcLsGGTzAjm3pCCq0CZCQrp6m.jpg,12444,해리 포터와 죽음의 성물 1,Harry Potter and the Deathly Hallows: Part 1,...,"[12, 14]",16.0929,2010-11-17,False,7.700,19830.0,모험 판타지,영어,해리 포터와 죽음의 성물 1 (Harry Potter and the Deathly ...,4.940675
5,2125,Ever After: A Cinderella Story (1998),Comedy Drama Romance,tt0120631,9454.0,False,/lhpokM60CnLWcNETQqKMz2q9ryL.jpg,9454,에버 애프터,EverAfter,...,"[18, 10749, 35]",3.3908,1998-07-31,False,7.439,1527.0,드라마 로맨스 코미디,영어,에버 애프터 (EverAfter),4.937487
6,261955,The Rescue (2021),Documentary Thriller,tt9098872,680058.0,False,/gOBKWe6lHlt8srk11TFlDuBtl0H.jpg,680058,위대한 구조,The Rescue,...,"[99, 18]",4.2165,2021-10-08,False,7.942,242.0,다큐멘터리 드라마,영어,위대한 구조 (The Rescue),4.927864
7,166643,Hidden Figures (2016),Drama,tt4846340,381284.0,False,/rfkIeCaIHhN3K5wjJJqKmfUjYp8.jpg,381284,히든 피겨스,Hidden Figures,...,"[18, 36]",54.8357,2016-12-10,False,8.050,10146.0,드라마 역사,영어,히든 피겨스 (Hidden Figures),4.924833
8,69844,Harry Potter and the Half-Blood Prince (2009),Adventure Fantasy Mystery Romance IMAX,tt0417741,767.0,False,/urDWNffjwmNi5IQaezw9GwqkUXa.jpg,767,해리 포터와 혼혈왕자,Harry Potter and the Half-Blood Prince,...,"[12, 14]",15.7831,2009-07-15,False,7.682,20221.0,모험 판타지,영어,해리 포터와 혼혈왕자 (Harry Potter and the Half-Blood P...,4.914753
9,2324,Life Is Beautiful (La Vita è bella) (1997),Comedy Drama Romance War,tt0118799,637.0,False,/6aNKD81RHR1DqUUa8kOZ1TBY1Lp.jpg,637,인생은 아름다워,La vita è bella,...,"[35, 18]",9.5737,1997-12-20,False,8.440,13604.0,코미디 드라마,이탈리아어,인생은 아름다워 (La vita è bella),4.906753